### ISSUE TITLE
ekf_nodeにimuのデータが含まれていない

### ISSUE THREAD

**Issue by kyo0221** [open-rdc/orne-box#105]
ekf_filter_nodeに/odomと/imu/dataを渡してセンサフュージョンすることを想定しているが, ekf_filter_nodeの出力である/odometry/filteredには/imuの値が適応されておらず/odomと同じ値が出てしまっている.

白 : /odom
赤 : /odometry/filtered
![Screenshot from 2024-09-26 18-22-20](https://github.com/user-attachments/assets/f41b8a5d-8ba1-47e2-bbf8-1131e0eee009)

```
ros2 topic info /odom
```
```
ros2 topic info /imu/data
```
でekf_filter_nodeがサブスクライブしていることは確認している.

ekf_filter_nodeに使われているekf.yamlの記述に問題があると思われる.
https://github.com/TakumiIshiguro/orne-box/blob/bag-fix/orne_box_bringup/config/robot_localization/ekf.yaml

**Comment by kyo0221** [comment]
ekf_filter_nodeのパラメータについて書いてあるドキュメント
https://docs.ros.org/en/melodic/api/robot_localization/html/state_estimation_nodes.html#ekf-localization-node

**Comment by kyo0221** [comment]
/odometry/filteredがIMUのヨー角の情報で動くようになった.
車輪を浮かせた状態で車輪を回したら/odomだけが回転することを確認した.

IMUが読み込めていなかったのはtfの問題のようだった.

白：/odom
赤：/odometry/filtered
![box3_ekf_3](https://github.com/user-attachments/assets/4adcdd2e-5d66-42ef-8c72-b276f2a86f80)

現状では/odometry/filteredの向きと進行方向が合っていない動きをしているので原因を探っている.

**Comment by kyo0221** [comment]
box2のtf
![box2_tf](https://github.com/user-attachments/assets/ddcfc329-b404-4eb9-8e29-9fa14589cdbc)
![box2_tf2](https://github.com/user-attachments/assets/87e59860-a38c-4dbe-8273-f481c83d06c4)

box3のtf
![box3_tf](https://github.com/user-attachments/assets/27253f89-2a1a-4bac-9b47-f8794c28eded)
![box3_tf2](https://github.com/user-attachments/assets/76537364-2790-4fcf-a06f-278e4d263933)

**Comment by TakumiIshiguro** [comment]
ac311e8e938fca0dcadc953cdfa839a17b845609
frame_idを変更した

変更後のrqt_tf_treeは以下のように変化した
![frames](https://github.com/user-attachments/assets/7ec6548e-dd77-4b91-ba8b-11aa0586fc41)

再び/odometry/filteredを確認すると/odomよりもきれいな軌跡が描けた
imuのキャリブレーションは行っていない
![Screenshot from 2024-10-02 18-17-16](https://github.com/user-attachments/assets/ad37e6ef-3e82-48a5-bda0-680460d5c891)

**Comment by kyo0221** [comment]
津田沼キャンパスの外周部分を1週させた/odometry/filteredの軌跡です.
IMUはキャリブレーション済みになっています.

![Screenshot from 2024-10-05 20-15-38](https://github.com/user-attachments/assets/6a73485c-ac00-47e8-b62d-3e5679dfeff8)

ekf_nodeでimuのデータを読み込めるようになったのでcloseします.
