### ISSUE TITLE
実機環境との統合作業

### ISSUE THREAD

**Issue by maHidaka** [open-rdc/orne-box#25]
現状orne-boxの実機で動作しているコードがこのリポジトリのコードと全くリンクしていないため、実機の環境をこのリポジトリに統合する必要がある
統合したあとはこのリポジトリをもとに実機の環境を管理する

**Comment by maHidaka** [comment]
ブランチ[old_dev/issue_25](https://github.com/open-rdc/orne-box/tree/old_dev/issue_25)へ統合前のコードを追加
現状このコードで動かしていた感じです

**Comment by taishiyamamoto** [comment]
orne_boxを動作させる上で不要だと思ったファイルを消去しました。
https://github.com/open-rdc/orne-box/pull/27
プルリクエストを投げたのでよろしければレビューお願いします。

**Comment by taishiyamamoto** [comment]
@maHidaka 
以下のブランチがマージされたのでcloseしてもよろしいでしょうか。
https://github.com/open-rdc/orne-box/pull/30
