### ISSUE TITLE
3D-LiDARの実装

### ISSUE THREAD

**Issue by IGC8810** [open-rdc/orne-box#28]
3D-LiDARであるR-Fans-16を実装
ナビゲーションに組込むまでの過程をWikiにまとめる

**Comment by taishiyamamoto** [comment]
実装しました．
これからWikiにまとめます．
https://youtu.be/bvi28ZU9-d0

**Comment by taishiyamamoto** [comment]
wikiにまとめました．
https://github.com/open-rdc/orne-box/wiki/Set-up-R-Fans-16
