### ISSUE TITLE
NVIDIA Jetson Xavier のセットアップ

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/orne-box#3]
NVIDIA Jetson Xavier のセットアップの方法を確認してメモを残す．

**Comment by yasuohayashibara** [comment]
出村先生が執筆したインストールの方法を発見．
参考にする．
https://demura.net/athome/15393.html

**Comment by yasuohayashibara** [comment]
@taishiyamamoto @tiger0421 
セットアップに関して知見が得られたらこちらに追加してもらえればと思います．

**Comment by taishiyamamoto** [comment]
出村先生が執筆したセットアップの方法はJetPackのバージョンが4.1.1ですが，自分たちは4.3でセットアップを行いました．
基本的な捜査の流れは同じだと思いますが，GUIに大きく変更が加わっています．
https://docs.nvidia.com/sdk-manager/install-with-sdkm-jetson/index.html

**Comment by taishiyamamoto** [comment]
セットアップの方法を記入しました．
https://docs.google.com/document/d/1yr4Er2KtaCM1qDe_Tm_X0hn2kUaMX4Est1JboUNOacU/edit?usp=sharing

**インストールできたホストPC環境**

- Lenovo ThinkBook13s(Intel® Core™ i7-8565U, Memory 16GB, GPU Intel® UHD Graphics)
- Ubuntu 18.04.4 LTS
- kernel 5.3.0-40-generic
- gcc/g++ 7.4.0

- Lenovo ThinkPad X240(Intel® Core™ i5-4300U, Memory 8GB, GPU Intel® Haswell Mobile)
- Ubuntu 18.04.4 LTS
- kernel 4.15.0-76-generic
- gcc/g++ 7.4.0

**Comment by yasuohayashibara** [comment]
Jetson Xavier agx のインストール
所要時間:約2時間
1.	nvidia_sdk_managerのサイトへ行く
https://developer.nvidia.com/nvidia-sdk-manager

![image](https://user-images.githubusercontent.com/5755200/76490522-b3909a80-646e-11ea-8307-2583f3b9c412.png)

2.	「Nvidia SDK Manager」をクリックすると，ログインすることを要求される．

![image](https://user-images.githubusercontent.com/5755200/76490529-bb503f00-646e-11ea-9d6c-f854b81f4a53.png)

3.	「log in」をクリックするとアドレスとパスワードの入力を要求されるので自分のアカウントでサインインする．（「join now」を押すと会員登録ページに飛ばされる）

![image](https://user-images.githubusercontent.com/5755200/76490545-c86d2e00-646e-11ea-907d-a9fb0a3b9c47.png)

4.	サインインするとマイページに飛ばされるので，上部にある「Nvidia SDK manager」をクリックする．

![image](https://user-images.githubusercontent.com/5755200/76490554-cc994b80-646e-11ea-9207-081269904713.png)

5.	押すと.debファイルをダウンロードできるので，ソフトウェアのインストールを行う． 

![image](https://user-images.githubusercontent.com/5755200/76490561-d4f18680-646e-11ea-9031-cdc1abe20f47.png)

6.	Nvidia SDK managerを起動する．

![image](https://user-images.githubusercontent.com/5755200/76490574-db7ffe00-646e-11ea-92ae-ff327fde4231.png)

7.	起動するとサインインを要求されるのでサインインする． 

![image](https://user-images.githubusercontent.com/5755200/76490589-e3d83900-646e-11ea-85d2-39d5a0e95fa6.png)

8.	　STEP 01で対象のハードウェア(Jetson Nano Jetson TX2 Jetson AGX Xavierなど)を選択できる．今回はJetson AGX Xavierを選択し，「CONTINUE」をクリック

![image](https://user-images.githubusercontent.com/5755200/76490597-e9ce1a00-646e-11ea-9eb1-12579797d07d.png)

9.	STEP 02でインストールするパッケージを選択できる．ページの下部に利用規約に同意するためのチェックボックスがあるのでそれをクリックし，「CONTINUE」を押す．  押すと19GB程のダウンロードが始まるので，ホストマシンの空き容量を確認する．

![image](https://user-images.githubusercontent.com/5755200/76490611-f488af00-646e-11ea-9165-2becdc125770.png)

10.	 ダウンロードが終わりインストールが始まり，しばらく経過すると，Jetsonのインストール方法を決める画面がポップアップする．

![image](https://user-images.githubusercontent.com/5755200/76490624-fc485380-646e-11ea-8b56-c9ebfeda8efd.png)

11.	ポップアップした画面にも書いてあるが，セットアップの方法を「Automatic Setup」から，「Manual Setup」にする．

![image](https://user-images.githubusercontent.com/5755200/76490641-079b7f00-646f-11ea-9e49-b415b48ad203.png)

12.	ここからはJetson AGX Xavierが必要になるため用意する．（ダウンロードを行っている間に行う方が時間の効率は良い）

13.	Jetson AGX Xavierを操作できる状態にする．｛セットアップにはACアダプタ（付属），キーボード，マウス（USBのポートが少ないのでハブが必要），インターネット（有線接続），モニター（HDMI），ホストマシンとXavierを繋ぐケーブル(付属の USB-TypeC to A)が必要｝

14.	接続後，Jetson AGX Xavierをセットアップできる状態にする．
まず，Force Recovery Buttonを押した状態を維持し，Power Buttonを押す．そして，Force Recovery ButtonとPower Buttonを離すという手順がいる．

![image](https://user-images.githubusercontent.com/5755200/76490664-15e99b00-646f-11ea-83f8-05e16913ea47.png)

15.	成功すると白い電源ランプが光り，ホストマシンでlsusbコマンドを叩くとNvidiaのデバイスが確認できる．
確認できたら，「Flash」をクリックする．

![image](https://user-images.githubusercontent.com/5755200/76490670-1d10a900-646f-11ea-9beb-2add6e7020a7.png)

![image](https://user-images.githubusercontent.com/5755200/76490684-2437b700-646f-11ea-9ec9-343bd9e5b700.png)

16.	しばらくすると，Jetson AGX Xavierが起動し，Ubuntuの初期設定の画面が出てくる．設定を完了すると，サインインできるようになる． 

![image](https://user-images.githubusercontent.com/5755200/76490710-2dc11f00-646f-11ea-9472-1e356b2400a7.png)

17.	その後，Jetson AGX XavierのIP AdressとUsername，Passwordの入力を要求されるので，先程設定したものを入力し，インストールする．
(IP Adressはデフォルトの192.168.55.1で問題なかった．)  

![image](https://user-images.githubusercontent.com/5755200/76490722-33b70000-646f-11ea-94ff-a4978d70bb0c.png)

18.	インストールが問題なく完了すると，以下のような画面になる．「FINISH」をクリックして終了する．

![image](https://user-images.githubusercontent.com/5755200/76490745-3d406800-646f-11ea-802e-21e6a5b8e817.png)

参考
●	Jetson AGX Xavier Developer Kit User Guide　https://developer.nvidia.com/embedded/dlc/jetson_agx_xavier_developer_kit_user_guide

**Comment by yasuohayashibara** [comment]
@taishiyamamoto ROSはインストールしました？

**Comment by tiger0421** [comment]
installROS.shをたたくだけでインストールできました．
https://github.com/jetsonhacks/installROSXavier

**Comment by yasuohayashibara** [comment]
問題あれば再度開くとしてissueを閉じます．
ご協力いただいたみなさまありがとうございます．
