### ISSUE TITLE
rfans16の点群データのフォーマット

### ISSUE THREAD

**Issue by IGC8810** [open-rdc/orne-box#45]
rfans16が出力する点群データのフォーマット形式がおかしい

**Comment by NaokiTakahashi12** [comment]
PointCloud2のfieldのnameとdatatypeが異なっている様です．
cloud_processノードで対処します．

**Comment by NaokiTakahashi12** [comment]
https://github.com/open-rdc/orne-box/pull/46 にてnodeを追加しました．
`rfans16.launch`を起動すると，`/rfans/surestar_points`が追加されていると思います．
どなたか，点群データフォーマットが望ましい形になっているか確認してください．
