### ISSUE TITLE
[GNSS] GNSSを使用した自律移動の問題

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/orne-box#69]
GNSSを使用した自律移動の問題点を議論するためのissue
大塚君関連のissueでORNE-boxには直接依存しないため，２月末には閉じる．

**Comment by yasuohayashibara** [comment]
ノードの構成

![image (2)](https://user-images.githubusercontent.com/5755200/215413728-4cfa09ab-60f5-4ed8-bdc5-26e23dd8b0eb.png)

**Comment by yasuohayashibara** [comment]
緯度
![latitude](https://user-images.githubusercontent.com/5755200/215414440-e72f6ccf-6e4a-495c-aab7-848c25cff485.png)

経度
![longitude](https://user-images.githubusercontent.com/5755200/215414484-674832e6-901c-4c2d-a28c-cc59c992c50f.png)

**Comment by yasuohayashibara** [comment]
/ublox/fix_velocity

![ubloxvelocity](https://user-images.githubusercontent.com/5755200/215415197-abf3ae72-b814-4de0-aa9f-c0f6e356b2a7.png)

**Comment by yasuohayashibara** [comment]
odom
位置
![odomposition](https://user-images.githubusercontent.com/5755200/215416217-7cfd6538-5416-46e7-9218-f6034a79fc24.png)

速度
![odomvelocity](https://user-images.githubusercontent.com/5755200/215416259-de1f97a4-9b76-4915-8a6b-d76cd33fa0d5.png)

**Comment by yasuohayashibara** [comment]
/odometry/gps

速度，角速度は0rad/s
![odometrygps](https://user-images.githubusercontent.com/5755200/215417016-cf6ecf4f-d2cc-44a0-8ffe-01e323812e05.png)

**Comment by yasuohayashibara** [comment]
/odometry/filtered
tf: /odom -> /base_link

![odometryfiltered](https://user-images.githubusercontent.com/5755200/215419745-3a7532a2-42b6-48f4-bb3e-1c8306ed3ba0.png)

**Comment by yasuohayashibara** [comment]
TFを表示してみた

[![IMAGE](http://img.youtube.com/vi/sBuVO7eBKIs/0.jpg)](https://youtu.be/sBuVO7eBKIs)

**Comment by yasuohayashibara** [comment]
問題点と思われるもの

１）odom -> base_link で矛盾した値が出力されている．
２）ロボットのヨー方向の姿勢が正確に推定されていない．

**Comment by yasuohayashibara** [comment]
![image](https://user-images.githubusercontent.com/5755200/215472894-1a955823-9b51-487c-9f25-850b4c889934.png)

元データ
[odom.xlsx](https://github.com/open-rdc/orne-box/files/10535587/odom.xlsx)

**Comment by ryuseiotsuka** [comment]
現在の状態です．
gnssの緯度経度情報のみを使って計算したodometry/gps（緑）の原点と回転方向の調整が終了しました．
odometry/gpsとIMU，ホイールオドムをekfで融合したodometry/filtered（黄）は，ロボットの実際の向きに関わらず右を向き続けてしまっています．
このロボットの方向の問題を修正すれば自律走行で使用できると思います．
![image](https://user-images.githubusercontent.com/50820803/216526120-96b6acaa-9592-4750-a2ba-636054bbec49.png)

**Comment by ryuseiotsuka** [comment]
IMUを抜いてrobot_localizationでセンサ値を融合したところロボットの姿勢の問題が見られなかったため，IMUの各軸の向きについて調整を行う．
![image](https://user-images.githubusercontent.com/50820803/216541779-5904e2d5-14c8-41f7-bf35-fbfa1c62248d.png)

**Comment by yasuohayashibara** [comment]
gazebo上で構築したシミュレータ環境のノードの繋がり

![rosgraph](https://user-images.githubusercontent.com/5755200/216805167-4da6e709-7a5e-4a06-8e11-74219218103e.png)

**Comment by yasuohayashibara** [comment]
GNSSをメインで使用するときにはこちらがおそらく正解

![rosgraph2](https://user-images.githubusercontent.com/5755200/216806968-1d6d40f0-0337-4046-8153-b934d0c7970a.png)

**Comment by yasuohayashibara** [comment]
#70 にシミュレータで検証した結果を載せました．

**Comment by yasuohayashibara** [comment]
実ロボットレベルでまだ問題は解決していませんが，開発はとりあえず終了したので，こちらのissueは閉じます．
