### ISSUE TITLE
Realsenseが認識されない

### ISSUE THREAD

**Issue by tiger0421** [open-rdc/orne-box#7]
RealsenseをUSBで接続し，lsusbコマンドを用いたが，本来出るはずの Inter Corp の表示がなかった．

**Comment by tiger0421** [comment]
USB3.0に対応していなかったことが原因．
USBハブがUSB3.0 に対応していれば認識される．
typeC to typeCにして接続することも可．

解決したので情報共有後，クローズ．

**Comment by yasuohayashibara** [comment]
issueをクローズします．
あと，どうも私以外クローズできないようですので，権限を見直します．
