### ISSUE TITLE
orne-box2に搭載されているGIGABYTEの電源がオペレータの操作なしで落ちる問題

### ISSUE THREAD

**Issue by hellocit** [open-rdc/orne-box#73]
使用したロボット：orne-box2
使用したコンピュータ：GIGABYTE
走行時の電圧計の値：24.2V（確実ではない）
非走行時の電圧計の値:24.8V

津田沼チャレンジに向けて走行の練習をしていた．津田沼チャレンジのコースにおいて，最後の白線の位置でオペレータが何も操作することなしにGIGABYTEの電源が落ちた．

**Comment by yasuohayashibara** [comment]
こちら既に使用していないコンピュータで情報共有も完了したと思いますので，issueを閉じます．
