### ISSUE TITLE
IMUのキャリブレーションの検証

### ISSUE THREAD

**Issue by Mochizuki12** [open-rdc/orne-box#74]
静止時にIMUのＺ軸回転のドリフトが原因でロボットの姿勢が回転する問題があったため，ADI_IMU_TR_Driver_ROS1のキャリブレーション機能を使用してキャリブレーションを行う．<ins>現在はこちらのキャリブレーション機能を使用している<ins/>．

過去120秒のデータを使用してキャリブレーションを行うため，120秒間静止させてからserviceをコールするとキャリブレーションを行える．
以下に現在のキャリブレーションを行う手順を示す．

１．script_orneの中にある, imu_calibration.shを実行．
２．120秒のカウントが始まるのでその間ロボットを動かさない．
３．calibration doneとの表示が出たらキャリブレーション完了．

以上の手順でキャリブレーションを行うことができる．
**ただし，box2の電源を落とすとキャリブレーションがリセットされるので，電源を入れたら毎回おこなう必要がある．**

動画
- 検証動画
[キャリブレーションの機能検証動画](https://www.youtube.com/watch?v=y12Iv_SJt-c)

- キャリブレーションなしの動画
[キャリブレーションなしの時のクォータニオンの変化の動画](https://www.youtube.com/watch?v=Smpm6d2wqQI)
[キャリブレーションなしの姿勢変化(rviz)](https://www.youtube.com/watch?v=tX71oiu0i94)

IMUのROS 1パッケージ
https://github.com/technoroad/ADI_IMU_TR_Driver_ROS1

コールするservice
```
$ rosservice call /imu/cmd_srv "cmd: 'START_BIAS_CORRECTION'
args:
- ''"
```

**Comment by Mochizuki12** [comment]
また，adi_driverのキャリブレーション機能を使用した結果を以下示す．現在のbox2のjetsonの環境ではadi_driverは使用できなかった．他のPCでは動作確認済み（melodic, noetic）．

adi_driverは過去40秒のデータを使用してキャリブレーションを行う．40秒間静止させてからserviceをコールするとキャリブレーションを行える．
**ただし，box2の電源を落とすとキャリブレーションがリセットされるので，電源を入れたら毎回おこなう必要がある．**

以下に実行した動画のURLを添付する．
https://www.youtube.com/watch?v=ont-yWjL6X0

使用したROS 1パッケージ
https://github.com/tork-a/adi_driver

コールするservice
```
rosservice call /imu/bias_estimate
```

**Comment by Mochizuki12** [comment]
IMUのキャリブレーションの効果を18階を1周した時のオドメトリとIMUで補正したオドメトリを表示して確認した．
現在のシステムでは，オドメトリのデータは，オドメトリの生データである odom とIMUのデータでオドメトリを補正した　odometry_filteredの2種類がある．

1．odom
<img width="418" alt="odom_no_filter_before1" src="https://github.com/open-rdc/orne-box/assets/92071009/f9460e98-df03-4320-819f-9bc11802d473">


2．キャリブレーション前のodometry_filtered
<img width="276" alt="odom_filtered_no_calib_before1" src="https://github.com/open-rdc/orne-box/assets/92071009/4215511e-6023-479b-8b41-91842febb1ef">

3．キャリブレーション後のodometry_filtered
<img width="383" alt="odom_filtered_calib_before1" src="https://github.com/open-rdc/orne-box/assets/92071009/2b27f8ec-8881-4f4b-975b-06504adaa8cb">

キャリブレーション前は閉じていなかったが，キャリブレーション後はループが閉じているため，キャリブレーションの効果があることがわかった．

**Comment by yasuohayashibara** [comment]
@Mochizuki12 Yuya Mochizuki
つくばチャレンジも終了したのでissueを閉じてください．

**Comment by yasuohayashibara** [comment]
以下，データとして追加しておく．
つくばチャレンジでのオドメトリの値

![Screenshot from 2023-11-20 20-37-45](https://github.com/open-rdc/orne-box/assets/5755200/6d5266b2-c075-4760-8276-a2cc29ecf136)

ちなみに，IMUを利用していないORNE-box3は以下のような感じ

![Screenshot from 2023-11-20 20-40-30](https://github.com/open-rdc/orne-box/assets/5755200/7c2069ec-b0b1-4dbe-944e-60d011c0af02)
