### ISSUE TITLE
TFにおけるリンク間の差を求めたい

### ISSUE THREAD

**Issue by nkm071** [open-rdc/orne-box#97]
base_linkのxとy座標の値-gnss_linkのxとy座標の値

上記の計算を行いたい．計算したい対象の画像とtfのツリーを以下に示す．
![293343723-991dd056-d426-436a-9c0b-e7b2faaf71da](https://github.com/open-rdc/orne-box/assets/91714744/373ffa61-5a92-4a04-a4c3-51592ed43878)

![293347591-2f882cba-d81d-40ba-afb7-1fd3949029d4](https://github.com/open-rdc/orne-box/assets/91714744/baaa59a4-0dac-4a38-b426-1b534072d6e5)

**Comment by nkm071** [comment]
[chatgptに作らせたスクリプト](https://github.com/hellocit/GNSS-research/blob/main/test/test.py)で解決している可能性もある．

**Comment by yasuohayashibara** [comment]
TFを用いた座標の変換ですが，上記のスクリプト「のような」処理でできると思います．
（確認していません．以前林原が座標変換を行ったときの構造と似ていますので．）
念のため，手計算で解いた座標と上記の計算結果が一致しているかどうかを確認してから進めたほうが良いと思います．
（間違った方法が提示されているおそれもありますので．）

**Comment by nkm071** [comment]
プリント文を用いたところ値が出力されました。

**Comment by hellocit** [comment]
<xacro:sensor_gnss name="gnss" parent="base_link">
    <origin xyz="-0.12 0.12 0.9" rpy="0 0 0"/>
  </xacro:sensor_gnss>

上記の値と一致していたので問題はないと考えます。

**Comment by hellocit** [comment]
あとはgnssの値をロボットのいる座標系に変換できればよいのか...

**Comment by nkm071** [comment]
https://github.com/open-rdc/orne-box/blob/39cc2e3171b137bfcf8c1c9087dae9fa7548f1ae/orne_box_description/urdf/orne_box_3d_lidar.urdf.xacro#L79C1-L82C23

xとy座標は上記の値と一致していたので差を求める計算には問題がないと考えます。

**Comment by yasuohayashibara** [comment]
解決したらissurを閉じていただいて構いません．

**Comment by nkm071** [comment]
承知しました．ありがとうございます．
